### ISSUE TITLE
The location of Firebird Client Library could not be determined

### ISSUE THREAD

**Issue by maponzzi** [FirebirdSQL/fdb#103]
I'm upgrading a django app from 1.8 to 2.2.24
This app uses: 
django-firebird==2.2a1
fdb==2.0.2

when I try to connect to DB I got this error:
_The location of Firebird Client Library could not be determined_

I'm working on a Macbook Air M1 mac OS 11.6 and I've installed Firebird-3.0.7-33374-x86_64.pkg from https://firebirdsql.org/en/firebird-3-0-7/#MacOS

any idea how to solve this ?

Thanks

**Comment by mrotteveel** [comment]
This looks more like a support question than a bug report. Could you ask your question on the [firebird-python Google Group](https://groups.google.com/g/firebird-python)?

**Comment by pcisar** [comment]
FDB uses standard ctypes.find_livrary() function to locate it, see https://docs.python.org/3.8/library/ctypes.html#finding-shared-libraries
It's also possible to specifi it directly via load_api() or connect() , see documentation for details. I have no idea how/whether this feature is surfaced in django.

**Comment by paulbeach** [comment]
<<FDB uses standard ctypes.find_livrary() function to locate it, see https://docs.python.org/3.8/library/ctypes.html#finding-shared-libraries
It's also possible to specifi it directly via load_api() or connect() , see documentation for details. I have no idea how/whether this feature is surfaced in django.>>

Firebird on MacOS is implemented as a Framework, the libfbclient.dylib library can be found in /Library/Frameworks/Firebird.framework/Libraries

**Comment by tomekki** [comment]
Dear both, 

could you provide an example please? In a similar environment, I have the also an issue when trying to configure the firebird api with an explicit lib location:

`con = fdb.connect(dsn="mydbname", user="user", password="pw",    fb_library_name="/Library/Frameworks/Firebird.framework/Versions/A/Resources/lib/libfbclient.dylib" ) `

Resuting in this error:
`
fdb.fbcore.DatabaseError: ('Error while connecting to database:\n- SQLCODE: -901\n- Error loading plugin Engine12\n- Module /Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib exists but can not be loaded\n- dlopen(/Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib, 1): Symbol not found: _fb_cancel_operation\n  Referenced from: /Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib\n  Expected in: flat namespace\n in /Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib', -901, 335545004) `

Thank you

**Comment by maponzzi** [comment]
I've also tried passing fb_library_name and got same error you got,
I've decide to change my computer and works fine, because I realised this is a particular issue with Macbook M1 chip

Thank you

**Comment by paulbeach** [comment]
<<I've also tried passing fb_library_name and got same error you got,
I've decide to change my computer and works fine, because I realised this is a particular issue with Macbook M1 chip
Thank you>>

Thats interesting, it looks like there is an issue with Rosetta in this particular case.
Can you try the following download and see if it solves the problem - its a native M1 Firebird for Mac
https://www.ibphoenix.com/downloads/Firebird-3.0.8-33398-M1.pkg

I did cross check libfbclient.dylib for 3.0.7 and the symbol _fb_cancel_operation is definitely exported.

Paul

**Comment by tomekki** [comment]
Hi Paul.
here is my result using Firebird-3.0.8-33398-M1.pkg:
`  File "./db-test.py", line 26, in main
    con = fdb.connect(
  File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 869, in connect
    raise exception_from_status(DatabaseError, _isc_status,
fdb.fbcore.DatabaseError: ('Error while connecting to database:\n- SQLCODE: -902\n- operating system directive access failed\n- Not a directory', -902, 335544373)`

/Tomekki

**Comment by paulbeach** [comment]
<<here is my result using Firebird-3.0.8-33398-M1.pkg:
File "./db-test.py", line 26, in main con = fdb.connect( File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 869, in connect raise exception_from_status(DatabaseError, _isc_status, fdb.fbcore.DatabaseError: ('Error while connecting to database:\n- SQLCODE: -902\n- operating system directive access failed\n- Not a directory', -902, 335544373)>>

Thats a completely different error, and is security related.
Before trying to connect to the database make sure /tmp/firebird has been deleted.
Then make sure that the firebird group or the relevant user etc has access to the database.
You can test if a database can be created and accessed simply by creatinf a database in isql
and then doing an embedded or remote connect to it.

Paul

**Comment by AlexPeshkoff** [comment]
On 11/17/21 11:17 AM, paulbeach wrote:
>
> <<here is my result using Firebird-3.0.8-33398-M1.pkg:
> File "./db-test.py", line 26, in main con = fdb.connect( File 
> ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 869, in 
> connect raise exception_from_status(DatabaseError, _isc_status, 
> fdb.fbcore.DatabaseError: ('Error while connecting to database:\n- 
> SQLCODE: -902\n- operating system directive access failed\n- Not a 
> directory', -902, 335544373)>>
>

Just 2 cents regarding error message - it's buggy here (message text is 
wrong, the fact of inability to access /tmp/firebird is detected 
cirrectly), fixed in https://github.com/FirebirdSQL/firebird/issues/7043

**Comment by tomekki** [comment]
Thank you for the tip @AlexPeshkoff. Knowing that access to /tmp/firebird is also needed, I added my user to the firebird group to avoid the -902 error. Also, I can access the db file using isql on my M1 now.

If I could just get fdb to work:
`
File "./db-test.py", line 37, in main
    cur.execute("select * from device;")
  File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 3688, in execute
    self._transaction.begin()
  File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 4169, in begin
    raise exception_from_status(DatabaseError, self._isc_status,
fdb.fbcore.DatabaseError: ('Error while starting transaction:\n- SQLCODE: -904\n- invalid database handle (no active connection)', -904, 335544324)
`

I time boxed my self to one hour and was not able to figure out how to avoid the new -904 error code.

This is my test code:
`import fdb
 con = fdb.connect(
                database='/opt/databases/mydb.fdb',
                user="mouser",
                password="mypw",
                charset="UTF8",
                fb_library_name="/Library/Frameworks/Firebird.framework/Versions/A/Resources/lib/libfbclient.dylib"
            )

print (con.db_info(fdb.isc_info_user_names)) # works

 cur = con.cursor()
 cur.execute("select * from device;")  # throws
print(cur.fetchall())`

So Firebird-3.0.8-33398-M1.pkg works well for me. Just the fdb driver is not working

**Comment by paulbeach** [comment]
<<Thank you for the tip @AlexPeshkoff. Knowing that access to /tmp/firebird is also needed, I added my user to the firebird group to avoid the -902 error. Also, I can access the db file using isql on my M1 now.
If I could just get fdb to work:

File "./db-test.py", line 37, in main cur.execute("select * from device;") File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 3688, in execute self._transaction.begin() File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 4169, in begin raise exception_from_status(DatabaseError, self._isc_status, fdb.fbcore.DatabaseError: ('Error while starting transaction:\n- SQLCODE: -904\n- invalid database handle (no active connection)', -904, 335544324)
I time boxed my self to one hour and was not able to figure out how to avoid the new -904 error code.
This is my test code:
`import fdb
con = fdb.connect(
database='/opt/databases/mydb.fdb',
user="mouser",
password="mypw",
charset="UTF8",
fb_library_name="/Library/Frameworks/Firebird.framework/Versions/A/Resources/lib/libfbclient.dylib"
)
print (con.db_info(fdb.isc_info_user_names)) # works
cur = con.cursor()
cur.execute("select * from device;") # throws
print(cur.fetchall())`>>

If you change 
database='/opt/databases/mydb.fdb',
to
database='localhost:/opt/databases/mydb.fdb',

What happens? The error seems to indicate that a transaction cannot be started because
there is no connection to the database.

Paul

**Comment by tomekki** [comment]
Hi @paulbeach.  `database='localhost:/opt/databases/mydb.fdb'` has the exact same exception with fdb:
```python
(.venv) % ./db-test.py
{'REMOTEK': 1}
Traceback (most recent call last):
  File "./db-test.py", line 40, in <module>
    main()
  File "./db-test.py", line 35, in main
    cur.execute("select * from device;")
  File ".../.venv/lib/python3.8/site-packages/fdb/fbcore.py", line 3688, in execute
    self._transaction.begin()
  File "....venv/lib/python3.8/site-packages/fdb/fbcore.py", line 4169, in begin
    raise exception_from_status(DatabaseError, self._isc_status,
fdb.fbcore.DatabaseError: ('Error while starting transaction:\n- SQLCODE: -904\n- invalid database handle (no active connection)', -904, 335544324)
```

`database='localhost:/opt/databases/mydb.fdb` works also with firebird-driver==1.3.3. This is why I would assume that the connection to the db is fine in principle.

**Comment by briosheje** [comment]
> Dear both,
> 
> could you provide an example please? In a similar environment, I have the also an issue when trying to configure the firebird api with an explicit lib location:
> 
> `con = fdb.connect(dsn="mydbname", user="user", password="pw", fb_library_name="/Library/Frameworks/Firebird.framework/Versions/A/Resources/lib/libfbclient.dylib" ) `
> 
> Resuting in this error: `fdb.fbcore.DatabaseError: ('Error while connecting to database:\n- SQLCODE: -901\n- Error loading plugin Engine12\n- Module /Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib exists but can not be loaded\n- dlopen(/Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib, 1): Symbol not found: _fb_cancel_operation\n Referenced from: /Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib\n Expected in: flat namespace\n in /Library/Frameworks/Firebird.framework/Versions/A/Resources/plugins/libEngine12.dylib', -901, 335545004)`
> 
> Thank you

This error in my case popped up targeting a docker container and having the docker container not ready to accept connection (because the file I was mounting was corrupted).

**Comment by devnoname120** [comment]
I have the same problem on macOS where both the Firebird server and my Python script run locally.

My configuration:
- MacBook Pro with Apple M2 Max (arm64 / Apple Silicon)
- macOS: `14.7.1` (Sonoma)
- Firebird: `5.0.1.1469` (arm64)
- Python: `3.12.8`
    - fdb: `2.0.2`

I confirm that I can indeed access the database via `isql` without any issues:
```shell
❯ isql -u sysdba -p masterkey inet4://localhost:3050//Users/paul/STTDB3.FDB5 
Database: inet4://localhost:3050//Users/paul/STTDB3.FDB5, User: SYSDBA

SQL> SELECT COUNT(*) FROM CHANNELS;

                COUNT 
===================== 
                    5 

```

However it doesn't work from Python. I wrote the following equivalent code:

```
import fdb

conn = fdb.connect(
    host='localhost',
    port=3050,
    database='/Users/paul/STTDB3.FDB5',
    user='sysdba',
    password='masterkey'
)

cursor = conn.cursor()
cursor.execute("SELECT COUNT(*) FROM PLAYLIST")
```

But when I run it it errors out on the last line:

```shell
❯ python3 script.py

Error: ('Error while starting transaction:\n- SQLCODE: -904\n- invalid database handle (no active connection)', -904, 335544324)
```

I have no idea why it doesn't work and the error message isn't very helpful…

Anyone has pointers to help me out?
