### ISSUE TITLE
German Umlaute in Database path

### ISSUE THREAD

**Issue by Tombo89** [FirebirdSQL/fdb#104]
Hello,

I'm trying to connect to a database wich has a german "ü" in its path.
I can't change the path of the database on the system. When i try to connect to the database it doesn't work.

the ü gets replaced with Ã¼

`import fdb

con = fdb.connect(
    dsn='localhost/5145:C:/xxx/xxx/ü/xx/xx.FDB',
    user='SYSDBA', password='masterkey'
  )`

> fdb.fbcore.DatabaseError: ('Error while connecting to database:\n- SQLCODE: -902\n- I/O error during "CreateFile (open)" operation for file "C:/xxx/xxx/Ã¼/xx/xx.FDB"\n- Error while trying to open file

if i copy the database to a path without ü it works, but this is not a option for my project.

I tried so much different things but can't get it working.

**Comment by pcisar** [comment]
Did you try [utf8params parameter for connect()](https://fdb.readthedocs.io/en/latest/reference.html#connect) and dsn in utf8?

**Comment by Tombo89** [comment]
Hello,

this is awkward, I've read this section of the readme many times yesturday but must have missed this parameter.
I set utf8params=True and it works.

Thanks for the hint :)
