### ISSUE TITLE
"invalid database handle (no active connection)" from MacOS with arm64 M1

### ISSUE THREAD

**Issue by shvilime** [FirebirdSQL/fdb#109]
Hi.
Python 3.9.9 with fdb 2.0.2
Firebird server version for arm64 from [this issue](https://github.com/FirebirdSQL/firebird/issues/7041).
I've got error fdb.fbcore.DatabaseError: ('Error while starting transaction:\n- SQLCODE: -904\n- invalid database handle (no active connection)', -904, 335544324) while execute this code below.
```
import fdb
con = fdb.connect(
    dsn='10.X.XX.111:/base/test.gdb',
    user='sysdba', password='password',
)
print (con.db_info(fdb.isc_info_user_names))   ## work

cur = con.cursor()
cur.execute("select 1 from rdb$database")    ## Error

print(cur.fetchall())
```
I tried to connect with isql and execute query. It works fine.

**Comment by pcisar** [comment]
1. I don't have access to Apple M1 server, so I can't even verify the issue.
2. FDB is a legacy driver for use with Firebird 2.5 and Python 2.7. For Python 3.8+ and Firebird 3+ please use new firebird-driver.
