### ISSUE TITLE
non-ascii  characters in database path causes file not found error 

### ISSUE THREAD

**Issue by aarsakian** [FirebirdSQL/fdb#112]
I want to extract the contentds of firebird database files, however when the path has Greek characters I get an error `the system cannot locate ... ` with error code -902.

This seems to be related to issue #104, so I tried setting utf8params to True but the error persists. I am on Windows Machine and the library I use has version 2.0.2.

**Comment by pcisar** [comment]
Hi, you should use the connection() with utf8params=True, and pass the database path in UTF8.
