### ISSUE TITLE
EventConduit's wait() method never exits on database disconnect

### ISSUE THREAD

**Issue by mr-rfh** [FirebirdSQL/fdb#114]
Hi. First I want to thank you for your great library.

And now to the problem:

```
import fdb

con = fdb.connect(database="somedb", user="name", password="pw", charset='UTF8')

with con.event_conduit( ('SYS$EVENT',) ) as conduit:
    print("Start wait")
    events = conduit.wait()
    print(events)
```

If connection to the firebird have been unexpectedly interrupted I see following exception from the thread in my console. 
```

Exception in thread Thread-1:
...
fdb.fbcore.DatabaseError: ('Error while waiting for events:\n- SQLCODE: 0\n- unknown ISC error 0', 0, 0)
```

But conduit.wait() neither returns nor throws exceptions, it just hangs infinitely. So the code above doesn't know something went wrong.

**Comment by pcisar** [comment]
Fix committed.
