### ISSUE TITLE
macOS — `SQLCODE: -904\n- invalid database handle (no active connection)`

### ISSUE THREAD

**Issue by devnoname120** [FirebirdSQL/fdb#118]
_Crossposted from https://github.com/FirebirdSQL/fdb/issues/103#issuecomment-2523735608_

I use macOS and both the Firebird server and Python script run locally.

My configuration:
- MacBook Pro with Apple M2 Max (arm64 / Apple Silicon)
- macOS: `14.7.1` (Sonoma)
- Firebird: `5.0.1.1469` (arm64)
- Python: `3.12.8`
    - fdb: `2.0.2`

However when I attempt to use `fdb` in order to connect to a Firebird database through a local server it doesn't work. I wrote the following code:

```python
import fdb

conn = fdb.connect(
    host='localhost',
    port=3050,
    database='/Users/paul/STTDB3.FDB5',
    user='sysdba',
    password='masterkey'
)

cursor = conn.cursor()
cursor.execute("SELECT COUNT(*) FROM PLAYLIST")
print(cursor.fetchone()[0])
```

And when I attempt to run it then an error happens on the `cursor.execute()` line:

```shell
❯ python3 script.py

Error: ('Error while starting transaction:\n- SQLCODE: -904\n- invalid database handle (no active connection)', -904, 335544324)
```

---------

I confirm that I can indeed access the database via `isql` without any issues:
```shell
❯ isql -u sysdba -p masterkey inet4://localhost:3050//Users/paul/STTDB3.FDB5 
Database: inet4://localhost:3050//Users/paul/STTDB3.FDB5, User: SYSDBA

SQL> SELECT COUNT(*) FROM CHANNELS;

                COUNT 
===================== 
                    5 

```

And interestingly, if I switch to the (unfortunately 10 times slower) [`firebirdsql` library](https://github.com/nakagami/pyfirebirdsql/) then it also works without issues so it really seems to be an issue with `fdb`:

```diff
- import fdb
+ import firebirdsql as fdb
```

Gives the following when run:
```shell
❯ python3 script.py

5
```

**Comment by pcisar** [comment]
FDB is a legacy driver, not actively maintained. Did you try the [firebird-driver](https://pypi.org/project/firebird-driver/), which is the official driver for Firebird 3+?

**Comment by devnoname120** [comment]
Thanks for the heads-up, I just did switch to `firebird-driver` and it works well. It's noticeably slower compared to FDB for my use case, but it's good enough!
