### ISSUE TITLE
Can not connect to Firebird 3.0

### ISSUE THREAD

**Issue by taich001** [FirebirdSQL/fdb#7]
Hi,

I run firebird 3 on ubuntu 18.04
Python 3.6
fdb 2.0.1

Firebid settings:
ServerMode = SuperClassic
WireCrypt = Disabled
WireCompression = false
AuthServer = Legacy_Auth, Srp, Win_Sspi
AuthClient = Legacy_Auth, Srp, Win_Sspi
UserManager = Legacy_UserManager, Srp

When I run "python3 setup.py test" I get this error.

running test
running egg_info
writing fdb.egg-info/PKG-INFO
writing dependency_links to fdb.egg-info/dependency_links.txt
writing requirements to fdb.egg-info/requires.txt
writing top-level names to fdb.egg-info/top_level.txt
reading manifest file 'fdb.egg-info/SOURCES.txt'
writing manifest file 'fdb.egg-info/SOURCES.txt'
running build_ext
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
test_basic (testfdb.TestArrays) ... ERROR
test_read_full (testfdb.TestArrays) ... ERROR
test_write_full (testfdb.TestArrays) ... ERROR
test_write_wrong (testfdb.TestArrays) ... ERROR
test_pyfb_17 (testfdb.TestBugs)
(PYFB-17) NOT NULL constraint + Insert Trigger ... ERROR
test_pyfb_22 (testfdb.TestBugs)
(PYFB-22) SELECT FROM VARCHAR COLUMN WITH TEXT LONGER THAN 128 CHARS RETURN EMPTY STRING ... ERROR
test_pyfb_25 (testfdb.TestBugs)
(PYFB-25) Trancate long text from VARCHAR(5000) ... ERROR
test_pyfb_30 (testfdb.TestBugs)
(PYFB-30) BLOBs are truncated at first zero byte ... ERROR
test_pyfb_34 (testfdb.TestBugs)
(PYFB-34) Server resources not released on PreparedStatement destruction ... ERROR
test_pyfb_35 (testfdb.TestBugs)
(PYFB-35) Call to fetch after a sql statement without a result should raise exception ... ERROR
test_pyfb_44 (testfdb.TestBugs)
(PYFB-44) Inserting a datetime.date into a TIMESTAMP column does not work ... ERROR
testBlob (testfdb.TestCharsetConversion) ... ERROR
testCharVarchar (testfdb.TestCharsetConversion) ... ERROR
test_octets (testfdb.TestCharsetConversion) ... ERROR
test_utf82win1250 (testfdb.TestCharsetConversion) ... ERROR
test_connect (testfdb.TestConnection) ... ERROR
test_connect_role (testfdb.TestConnection) ... ERROR
test_database_info (testfdb.TestConnection) ... ERROR
test_db_info (testfdb.TestConnection) ... ERROR
test_execute_immediate (testfdb.TestConnection) ... ERROR
test_info_attributes (testfdb.TestConnection) ... ERROR
test_properties (testfdb.TestConnection) ... ERROR
test_transaction (testfdb.TestConnection) ... ERROR
testConnectSchema (testfdb.TestConnectionWithSchema) ... ERROR
test_create_drop (testfdb.TestCreateDrop) ... ERROR
test_description (testfdb.TestCursor) ... ERROR
test_exec_after_close (testfdb.TestCursor) ... ERROR
test_executemany (testfdb.TestCursor) ... ERROR
test_fetchall (testfdb.TestCursor) ... ERROR
test_fetchallmap (testfdb.TestCursor) ... ERROR
test_fetchmany (testfdb.TestCursor) ... ERROR
test_fetchmanymap (testfdb.TestCursor) ... ERROR
test_fetchone (testfdb.TestCursor) ... ERROR
test_fetchonemap (testfdb.TestCursor) ... ERROR
test_iteration (testfdb.TestCursor) ... ERROR
test_iteration (testfdb.TestCursor) ... ERROR
test_name (testfdb.TestCursor) ... ERROR
test_rowcount (testfdb.TestCursor) ... ERROR
test_use_after_close (testfdb.TestCursor) ... ERROR
test_context_manager (testfdb.TestDistributedTransaction) ... ERROR
test_limbo_transactions (testfdb.TestDistributedTransaction) ... ERROR
test_simple_dt (testfdb.TestDistributedTransaction) ... ERROR
test_20_events (testfdb.TestEvents) ... ERROR
test_flush_events (testfdb.TestEvents) ... ERROR
test_multiple_events (testfdb.TestEvents) ... ERROR
test_one_event (testfdb.TestEvents) ... ERROR
test_locale (testfdb.TestGstatParse) ... ERROR
test_parse25_a (testfdb.TestGstatParse) ... ERROR
test_parse25_d (testfdb.TestGstatParse) ... ERROR
test_parse25_f (testfdb.TestGstatParse) ... ERROR
test_parse25_h (testfdb.TestGstatParse) ... ERROR
test_parse25_i (testfdb.TestGstatParse) ... ERROR
test_parse25_r (testfdb.TestGstatParse) ... ERROR
test_parse25_s (testfdb.TestGstatParse) ... ERROR
test_parse30_a (testfdb.TestGstatParse) ... ERROR
test_parse30_d (testfdb.TestGstatParse) ... ERROR
test_parse30_e (testfdb.TestGstatParse) ... ERROR
test_parse30_f (testfdb.TestGstatParse) ... ERROR
test_parse30_h (testfdb.TestGstatParse) ... ERROR
test_parse30_i (testfdb.TestGstatParse) ... ERROR
test_parse30_r (testfdb.TestGstatParse) ... ERROR
test_parse30_s (testfdb.TestGstatParse) ... ERROR
test_hook_db_attach_request (testfdb.TestHooks) ... ERROR
test_hook_db_attached (testfdb.TestHooks) ... ERROR
test_hook_service_attached (testfdb.TestHooks) ... ERROR
test_insert_blob (testfdb.TestInsertData) ... ERROR
test_insert_boolean (testfdb.TestInsertData) ... ERROR
test_insert_char_varchar (testfdb.TestInsertData) ... ERROR
test_insert_datetime (testfdb.TestInsertData) ... ERROR
test_insert_float_double (testfdb.TestInsertData) ... ERROR
test_insert_integers (testfdb.TestInsertData) ... ERROR
test_insert_numeric_decimal (testfdb.TestInsertData) ... ERROR
test_insert_returning (testfdb.TestInsertData) ... ERROR
TestLinuxDirect (testfdb.TestLogParse) ... ERROR
TestWindowsService (testfdb.TestLogParse) ... ERROR
test_locale (testfdb.TestLogParse) ... ERROR
testAttachmentInfo (testfdb.TestMonitor) ... ERROR
testCallStackInfo (testfdb.TestMonitor) ... ERROR
testContextVariableInfo (testfdb.TestMonitor) ... ERROR
testDatabaseInfo (testfdb.TestMonitor) ... ERROR
testIOStatsInfo (testfdb.TestMonitor) ... ERROR
testMonitor (testfdb.TestMonitor) ... ERROR
testMonitorBindClose (testfdb.TestMonitor) ... ERROR
.
.
.
.

======================================================================
ERROR: test_basic (testfdb.TestArrays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/x/fdb/test/testfdb.py", line 1106, in setUp
    super(TestArrays, self).setUp()
  File "/x/fdb/test/testfdb.py", line 116, in setUp
    with closing(fdb.services.connect(host=FBTEST_HOST, password=FBTEST_PASSWORD)) as svc:
  File "/x/fdb/fdb/services.py", line 213, in connect
    con = Connection(host, user, password)
  File "/x/fdb/fdb/services.py", line 261, in __init__
    "Services/isc_service_attach:")
fdb.fbcore.DatabaseError: ('Services/isc_service_attach:\n- SQLCODE: -902\n- Unable to complete network request to host "localhost".\n- Failed to establish a connection.', -902, 33554472

**Comment by kai3341** [comment]
@taich0001 why all test failure did not surprise you? Did you read exception message? It tells, that fdb can not connect firebird database. Did you install it from repository or using docker?

**Comment by taich001** [comment]
I copied the 5 fbtest databases to the database dir and I can open it.

isql-fb fbtest30.fdb
Database: fbtest30.fdb, User: SYSDBA
SQL> show tables;
       AR                                     COUNTRY
       CUSTOMER                               DEPARTMENT
       EMPLOYEE                               EMPLOYEE_PROJECT
       JOB                                    PROJECT
       PROJ_DEPT_BUDGET                       SALARY_HISTORY
       SALES                                  T
       T2                                     T3
       T4                                     T5

There are some other databeses, they also wont open.
Working with these DB's in perl is no problem.

**Comment by mrotteveel** [comment]
@taich001 With that ISQL connection you are using an embedded connection. Embedded also works if Firebird is not running. With your FDB connection you are connecting using TCP/IP to Firebird on port 3050. For that to work, the Firebird service must be started (and listening on port 3050).

However, this sounds more like a support question than a bug report. You might want to post to the firebird-python mailing list instead.

**Comment by taich001** [comment]
I solved it. Firebird was not listening on localhost. I removed RemoteBindAddress in firebird.conf and it works now.
Thanks for this advice.
