### ISSUE TITLE
ReferenceError exception when closing weakly referenced cursor [PYFB81]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/fdb#96]
Submitted by: Anders Munch (Flonidan) (ajm_flonidan)

Votes: 1

In have an application where I put database cursors in a weakref\.WeakSet in order to track database activity\.  It works fine with other DBAPI modules such as pypyodbc\.  With fdb I sometimes get a traceback when closing a cursor that ends like this:

File "C:\\flonidan\\env\\Python38\-64\\lib\\site\-packages\\fdb\\<http://fbcore.py>", line 3643, in close
    if is\_dead\_proxy\(self\.\_ps\):
  File "C:\\flonidan\\env\\Python38\-64\\lib\\site\-packages\\fdb\\<http://fbcore.py>", line 481, in is\_dead\_proxy
    return isinstance\(obj, weakref\.ProxyType\) and not dir\(obj\)
ReferenceError: weakly\-referenced object no longer exists

The apparent cause is a the is\_dead\_proxy function \(<http://fbcore.py> line 479\), which mysteriously uses "not dir\(obj\)" to check for a dead proxy\. Changing is\_dead\_proxy to catch ReferenceError seems to fix it:

def is\_dead\_proxy\(obj\):
    "Return True if object is a dead :func:\`weakref\.proxy\`\."
    try:
        return isinstance\(obj, weakref\.ProxyType\) and not dir\(obj\)
    except ReferenceError:
        return True

**Comment by hmoffatt** [comment]
I am having this problem with FDB used from SQL Alchemy now that I've upgraded to Python 3.9.

**Comment by pcisar** [comment]
fix adopted.
